name: rawg_dart_wrapper
description: A Dart & Flutter package to enable users to easily integrate the RAWG API and easily get details on games, trophies, platforms and more.

version: 1.3.0
repository: https://github.com/IsD4n73/RAWG_dart_wrapper/


environment:
  sdk: ^3.0.6

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

topics:
  - api
  - wrapper
  - games
  - rawg
