name: rawg_dart_wrapper
description: A Dart package to let users easily integrate RAWG API.

version: 1.0.0
repository: https://github.com/IsD4n73/RAWG_dart_wrapper/


environment:
  sdk: ^3.0.6

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

topics:
  - api
  - wrapper
  - games
  - RAWG
